### ISSUE TITLE
this or thefire

### ISSUE THREAD

**Issue by saberzaid** [CoolHandSquid/HackTricks-Automatic-Commands#2]
hello 

i took a look into both tool , this and the  thefire , looks similar or same 

what tool is best ?

**Comment by CoolHandSquid** [comment]
This repository should have been created as a fork of TireFire. They are basically identical at the moment.
TireFire will continue to receive updates (weekly at a minimum), and this repo will be removed shortly.
https://github.com/CoolHandSquid/TireFire is what you want.
I appreciate your support!
